# Generated by Django 5.1.5 on 2025-05-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='group_size',
            field=models.IntegerField(default=1),
        ),
    ]
