# Generated by Django 5.1.5 on 2025-05-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_amenities_room_bed_configuration_room_layout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
